onboarding = false

[theme]
name = "catppuccin"

[ui.sound]
enabled = false

[ui.toast]
delivery = "herdr"
delay_seconds = 2

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"
host_cursor = "drawn"
hide_tab_bar_when_single_tab = true
pane_scrollbars = false
