alias cat="bat --plain"
alias codexq="codex --profile quick"
alias gaa="git add --all"
alias gcmsg="git commit --message"
alias ggp="git push"
alias glods='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short'
alias k="kubecolor"
alias kctx="kubectx"
alias kns="kubens"
alias ll="ls -lah"
alias ls="lsd"
alias ofd="open ."
alias todo="rg \"TODO\" --colors match:fg:yellow --colors match:style:bold"
alias vim="nvim"
