cask_args appdir: "/Applications", require_sha: true

tap "aws/tap"
tap "buildkite/cli"
tap "common-fate/granted"
tap "gjbae1212/gossm"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "ack"
brew "age"
brew "aws-sam-cli"
brew "awscli"
brew "bk"
brew "chezmoi"
brew "coreutils"
brew "crane"
brew "curl"
brew "diff-so-fancy"
brew "dive"
brew "docker-credential-helper-ecr"
brew "exa"
brew "fd"
brew "git"
brew "glow"
brew "gnupg"
brew "go"
brew "gossm"
brew "granted"
brew "hadolint"
brew "helm"
brew "htop"
brew "httpie"
brew "hugo"
brew "jq"
brew "kcat"
brew "kind"
brew "kubectx"
brew "kubernetes-cli"
brew "kyverno"
brew "mas"
brew "mongosh"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "nvm"
brew "openssl"
brew "pre-commit"
brew "python@3.10"
brew "semgrep"
brew "shellcheck"
brew "starship"
brew "staticcheck"
brew "terraform-docs"
brew "testkube"
brew "tfenv"
brew "tflint"
brew "tfsec"
brew "tmux"
brew "wget"
brew "yarn", args: ["ignore-dependencies"]
brew "ykman"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password-cli"
cask "appcleaner"
cask "discord"
cask "docker"
cask "firefox"
cask "font-hack"
cask "font-meslo-for-powerline"
cask "gitify"
cask "google-chrome"
cask "google-cloud-sdk"
cask "insomnia"
cask "iterm2"
cask "keybase"
cask "logitech-options"
cask "mongodb-compass"
cask "notion"
cask "postico"
cask "raycast"
cask "rectangle"
cask "signal"
cask "slack"
cask "tailscale"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

# installed from the app store
mas "Amphetamine", id: 937984704
mas "Meeter", id: 1510445899
