cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "ack"
brew "aws-sam-cli"
brew "awscli"
brew "bk"
brew "coreutils"
brew "curl"
brew "docker"
brew "git"
brew "go"
brew "htop"
brew "httpie"
brew "hugo"
brew "jq"
brew "mas"
brew "nmap"
brew "nvm"
brew "openssl"
brew "python@3.8"
brew "shellcheck"
brew "tfenv"
brew "tmux"
brew "wget"
brew "yarn"

cask "docker"
cask "firefox-developer-edition"
cask "font-hack"
cask "gitify"
cask "google-chrome"
cask "iterm2"
cask "lepton"
cask "logitech-options"
cask "postman"
cask "private-internet-access"
cask "rectangle"
cask "signal"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "vlc"