format = """
$battery\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$kubernetes\
$aws\
$line_break\
$character"""

[aws]
format = ' on [$symbol($profile)]($style)'
style = "bold yellow"

[[battery.display]]
threshold = 20

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"

[git_branch]
symbol = "🌱 "

[kubernetes]
disabled = false
format = '| [$symbol$context( \($namespace\))]($style)'
symbol = "⛵ "

[nodejs]
symbol = "🤖 "

# disable unused modules

[crystal]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[shell]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[username]
disabled = true

[zig]
disabled = true