# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$battery\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$kubernetes\
$aws\
$line_break\
$character"""

palette = "catppuccin_mocha"

[[battery.display]]
threshold = 20

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"

[directory]
read_only = " 󰌾"
truncation_length = 4
style = "bold lavender"

[git_branch]
symbol = " "
style = "bold mauve"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
style = "bold teal"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[aws]
disabled = true
format = ' [$symbol($profile)]($style)'

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cpp]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[gcloud]
disabled = true

[git_commit]
disabled = true

[golang]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[hg_branch]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pixi]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[zig]
disabled = true

[gradle]
disabled = true
